Downgrade boto3
Upgrading to 1.36.x produces

```
Traceback (most recent call last):
File
"/home/mlaure/.local/share/virtualenvs/acceslibre-D3SEUTJ3/lib/python3.12/site-packages/celery/app/trace.py",
line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
File "/home/mlaure/dev/acceslibre/erp/export/tasks.py", line 36, in
generate_csv_file
s3.put_object(Bucket=bucket_name, Key=file_name, Body=csv_buffer.getvalue(),
ContentType="text/csv")
File
"/home/mlaure/.local/share/virtualenvs/acceslibre-D3SEUTJ3/lib/python3.12/site-packages/botocore/client.py",
line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File
"/home/mlaure/.local/share/virtualenvs/acceslibre-D3SEUTJ3/lib/python3.12/site-packages/botocore/client.py",
line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidArgument) when
calling the PutObject operation: Invalid Argument.
```